do $$
declare
  lv uuid; un uuid; ls uuid; ex uuid; nxt int;
begin
  select id into lv from levels where slug = 'elementary';
  select coalesce(max(order_index),0) into nxt from units where level_id = lv;
  nxt := nxt + 1;
  insert into units (level_id,name,slug,icon,order_index) values (lv,'날씨와 계절 (Weather & Seasons)','weather','cloud-sun',nxt) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'날씨 표현 (Talking about weather)','standard',null,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'날씨','weather','nalssi',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'더워요','it''s hot','deowoyo',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'추워요','it''s cold','chuwoyo',null,null,3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'비가 와요','it''s raining','biga wayo',null,null,4);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'It''s snowing outside. Which do you say?',null,'["눈이 와요", "비가 와요", "더워요"]'::jsonb,'눈이 와요',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'계절 (The four seasons)','standard',null,2) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'봄','spring','bom',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'여름','summer','yeoreum',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'가을','autumn','ga-eul',null,null,3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'겨울','winter','gyeoul',null,null,4);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'sentence_build',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Build: "Summer is hot."',null,'["여름은", "더워요"]'::jsonb,'여름은 더워요',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'날씨 맞추기 (Weather Match)','unlock_game',80,3) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'봄',null,null,null,'spring',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'여름',null,null,null,'summer',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'가을',null,null,null,'autumn',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'겨울',null,null,null,'winter',4);
  nxt := nxt + 1;
  insert into units (level_id,name,slug,icon,order_index) values (lv,'아파요 (Health & the Pharmacy)','health','stethoscope',nxt) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'몸 (Body parts)','standard',null,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'머리','head','meori',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'배','stomach','bae',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'목','throat/neck','mok',null,null,3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'아파요','it hurts','apayo',null,null,4);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'sentence_build',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Build: "My head hurts."',null,'["머리가", "아파요"]'::jsonb,'머리가 아파요',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'-아/어야 돼요 (You have to...)','standard',null,2) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'약','medicine','yak',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'쉬어야 돼요','you have to rest','swieoya dwaeyo',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'병원','hospital/clinic','byeongwon',null,null,3);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'The doctor tells you that you must rest. Which fits?',null,'["쉬어야 돼요", "쉬고 싶어요", "쉴까요?"]'::jsonb,'쉬어야 돼요',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'병원 롤플레이 (Clinic Roleplay)','unlock_game',80,3) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'머리',null,null,null,'head',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'배',null,null,null,'stomach',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'약',null,null,null,'medicine',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'아파요',null,null,null,'it hurts',4);
  nxt := nxt + 1;
  insert into units (level_id,name,slug,icon,order_index) values (lv,'어떻게 가요? (Getting Around)','transport','bus',nxt) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'교통수단 (Transport)','standard',null,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'버스','bus','beoseu',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'지하철','subway','jihacheol',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'택시','taxi','taeksi',null,null,3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'걸어서','on foot','georeoseo',null,null,4);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'sentence_build',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Build: "I go by bus."',null,'["버스로", "가요"]'::jsonb,'버스로 가요',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'길 묻기 (Asking directions)','standard',null,2) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'어떻게 가요?','How do I get there?','eotteoke gayo?',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'왼쪽','left','oenjjok',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'오른쪽','right','oreunjjok',null,null,3);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'You want to ask how to get to the station. Which do you say?',null,'["어떻게 가요?", "얼마예요?", "뭐예요?"]'::jsonb,'어떻게 가요?',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'교통 짝짓기 (Transport Match)','unlock_game',80,3) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'버스',null,null,null,'bus',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'지하철',null,null,null,'subway',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'택시',null,null,null,'taxi',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'왼쪽',null,null,null,'left',4);
  nxt := nxt + 1;
  insert into units (level_id,name,slug,icon,order_index) values (lv,'얼마예요? (Shopping & Prices)','shopping','shopping-bag',nxt) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'숫자와 가격 (Numbers & prices)','standard',null,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'얼마예요?','How much is it?','eolmayeyo?',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'천 원','1,000 won','cheon won',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'만 원','10,000 won','man won',null,null,3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'비싸요','it''s expensive','bissayo',null,null,4);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'You think the price is too high. Which do you say?',null,'["비싸요", "싸요", "맛있어요"]'::jsonb,'비싸요',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'-아/어 주세요 (Please do...)','standard',null,2) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'깎아 주세요','please give me a discount','kkakka juseyo',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'주세요','please give me','juseyo',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'이거 주세요','I''ll take this one','igeo juseyo',null,null,3);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'sentence_build',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Build: "Please give me this one."',null,'["이거", "주세요"]'::jsonb,'이거 주세요',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'시장 게임 (Market Game)','unlock_game',80,3) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'얼마예요?',null,null,null,'How much is it?',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'비싸요',null,null,null,'it''s expensive',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'주세요',null,null,null,'please give me',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'만 원',null,null,null,'10,000 won',4);
  nxt := nxt + 1;
  insert into units (level_id,name,slug,icon,order_index) values (lv,'레벨 시험 (Level Test)','test-elementary','flag',nxt) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'Elementary 레벨 시험 (Elementary Level Test)','level_test',80,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'It''s raining. Which is correct?',null,'["비가 와요", "더워요", "봄이에요"]'::jsonb,'비가 와요',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Your stomach hurts. Which is correct?',null,'["배가 아파요", "머리가 아파요", "약이에요"]'::jsonb,'배가 아파요',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',3) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'How do you ask the price?',null,'["얼마예요?", "어떻게 가요?", "뭐예요?"]'::jsonb,'얼마예요?',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',4) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'여름',null,null,null,'summer',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'지하철',null,null,null,'subway',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'약',null,null,null,'medicine',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'비싸요',null,null,null,'it''s expensive',4);
  select id into lv from levels where slug = 'intermediate';
  select coalesce(max(order_index),0) into nxt from units where level_id = lv;
  nxt := nxt + 1;
  insert into units (level_id,name,slug,icon,order_index) values (lv,'한국 문화 (Culture & Customs)','culture','landmark',nxt) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'-기 때문에 (Because...)','standard',null,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'문화','culture','munhwa',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'전통','tradition','jeontong',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'예의','manners/etiquette','ye-ui',null,null,3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'때문에','because of','ttaemune',null,null,4);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'sentence_build',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Build: "Because it''s a tradition."',null,'["전통이기", "때문이에요"]'::jsonb,'전통이기 때문이에요',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'명절 (Holidays)','standard',null,2) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'설날','Lunar New Year','seollal',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'추석','harvest festival','chuseok',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'세배','New Year bow','sebae',null,null,3);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Which holiday is the autumn harvest festival?',null,'["추석", "설날", "생일"]'::jsonb,'추석',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'문화 짝짓기 (Culture Match)','unlock_game',80,3) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'설날',null,null,null,'Lunar New Year',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'추석',null,null,null,'harvest festival',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'전통',null,null,null,'tradition',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'예의',null,null,null,'manners',4);
  nxt := nxt + 1;
  insert into units (level_id,name,slug,icon,order_index) values (lv,'-(으)면 어떻게 해요? (Conditions & Plans)','conditions','git-branch',nxt) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'-(으)면 (If...)','standard',null,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'시간이 있으면','if you have time','sigani isseumyeon',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'비가 오면','if it rains','biga omyeon',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'만약','if/supposing','manyak',null,null,3);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'sentence_build',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Build: "If you have time, let''s meet."',null,'["시간이 있으면", "만나요"]'::jsonb,'시간이 있으면 만나요',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'-(으)려고 하다 (Intending to)','standard',null,2) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'가려고 해요','I intend to go','garyeogo haeyo',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'계획','plan','gyehoek',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'준비하다','to prepare','junbihada',null,null,3);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'You intend to go to Korea next year. Which fits?',null,'["가려고 해요", "가고 싶어요", "갈까요?"]'::jsonb,'가려고 해요',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'계획 게임 (Planning Game)','unlock_game',80,3) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'계획',null,null,null,'plan',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'준비하다',null,null,null,'to prepare',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'만약',null,null,null,'if/supposing',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'가려고 해요',null,null,null,'I intend to go',4);
  nxt := nxt + 1;
  insert into units (level_id,name,slug,icon,order_index) values (lv,'들었어요 (Reported Speech)','reported','message-square',nxt) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'-다고 하다 (They said that...)','standard',null,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'-다고 해요','they say that...','-dago haeyo',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'들었어요','I heard','deureosseoyo',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'말했어요','said','malhaesseoyo',null,null,3);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'You heard that the exam is difficult. Which fits?',null,'["시험이 어렵다고 해요", "시험이 어려워요", "시험이 어려울까요?"]'::jsonb,'시험이 어렵다고 해요',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'의견 전하기 (Passing on opinions)','standard',null,2) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'-냐고 해요','they ask whether...','-nyago haeyo',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'소식','news','sosik',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'확실해요','it''s certain','hwaksilhaeyo',null,null,3);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'sentence_build',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Build: "I heard the news."',null,'["소식을", "들었어요"]'::jsonb,'소식을 들었어요',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'전달 게임 (Relay Game)','unlock_game',80,3) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'들었어요',null,null,null,'I heard',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'말했어요',null,null,null,'said',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'소식',null,null,null,'news',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'확실해요',null,null,null,'it''s certain',4);
  nxt := nxt + 1;
  insert into units (level_id,name,slug,icon,order_index) values (lv,'레벨 시험 (Level Test)','test-intermediate','flag',nxt) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'Intermediate 레벨 시험 (Intermediate Level Test)','level_test',80,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'"Because it''s a tradition" — which is correct?',null,'["전통이기 때문이에요", "전통이에요", "전통이면 돼요"]'::jsonb,'전통이기 때문이에요',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'"If it rains" — which is correct?',null,'["비가 오면", "비가 와요", "비가 올까요?"]'::jsonb,'비가 오면',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',3) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Report that someone said the exam is hard:',null,'["시험이 어렵다고 해요", "시험이 어려워요", "시험이 어렵지요?"]'::jsonb,'시험이 어렵다고 해요',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',4) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'추석',null,null,null,'harvest festival',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'계획',null,null,null,'plan',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'들었어요',null,null,null,'I heard',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'예의',null,null,null,'manners',4);
  select id into lv from levels where slug = 'upper-intermediate';
  select coalesce(max(order_index),0) into nxt from units where level_id = lv;
  nxt := nxt + 1;
  insert into units (level_id,name,slug,icon,order_index) values (lv,'사회 문제 (Social Issues & Debate)','social-issues','scale',nxt) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'-(으)ㄴ/는데도 (Even though)','standard',null,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'사회','society','sahoe',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'문제','issue/problem','munje',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'환경','environment','hwangyeong',null,null,3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'-는데도','even though','-neundedo',null,null,4);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'sentence_build',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Build: "Even though I studied, it was hard."',null,'["공부했는데도", "어려웠어요"]'::jsonb,'공부했는데도 어려웠어요',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'토론 표현 (Debate phrases)','standard',null,2) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'찬성해요','I''m in favour','chanseonghaeyo',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'반대 의견','opposing view','bandae uigyeon',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'근거','grounds/evidence','geun-geo',null,null,3);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'You support the proposal. Which fits?',null,'["찬성해요", "반대해요", "몰라요"]'::jsonb,'찬성해요',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'토론 짝짓기 (Debate Match)','unlock_game',80,3) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'사회',null,null,null,'society',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'환경',null,null,null,'environment',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'찬성해요',null,null,null,'I''m in favour',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'근거',null,null,null,'evidence',4);
  nxt := nxt + 1;
  insert into units (level_id,name,slug,icon,order_index) values (lv,'면접과 직장 (Interviews & Work)','work','briefcase',nxt) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'직장 어휘 (Workplace vocabulary)','standard',null,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'면접','job interview','myeonjeop',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'경험','experience','gyeongheom',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'회의','meeting','hoe-ui',null,null,3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'동료','colleague','dongryo',null,null,4);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'sentence_build',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Build: "I have experience."',null,'["경험이", "있습니다"]'::jsonb,'경험이 있습니다',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'존댓말 (Formal register)','standard',null,2) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'-습니다','formal statement ending','-seumnida',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'잘 부탁드립니다','I look forward to working with you','jal butakdeurimnida',null,null,2);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'In a job interview, which ending is most appropriate?',null,'["-습니다", "-아/어요", "-야"]'::jsonb,'-습니다',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'면접 롤플레이 (Interview Roleplay)','unlock_game',80,3) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'면접',null,null,null,'job interview',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'경험',null,null,null,'experience',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'회의',null,null,null,'meeting',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'동료',null,null,null,'colleague',4);
  nxt := nxt + 1;
  insert into units (level_id,name,slug,icon,order_index) values (lv,'조언과 제안 (Advice & Suggestions)','advice2','lightbulb',nxt) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'-도록 하다 복습 (Advice review)','standard',null,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'추천해요','I recommend','chucheonhaeyo',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'-는 게 어때요?','how about doing...?','-neun ge eottaeyo?',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'도움','help','doum',null,null,3);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Suggest that your friend try resting. Which fits?',null,'["쉬는 게 어때요?", "쉬어야 돼요", "쉬었어요"]'::jsonb,'쉬는 게 어때요?',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'격식 있는 요청 (Formal requests)','standard',null,2) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'부탁드립니다','I kindly ask','butakdeurimnida',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'가능할까요?','would it be possible?','ganeunghalkkayo?',null,null,2);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'sentence_build',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Build: "Would it be possible?"',null,'["가능할까요?"]'::jsonb,'가능할까요?',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'조언 게임 (Advice Game)','unlock_game',80,3) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'추천해요',null,null,null,'I recommend',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'도움',null,null,null,'help',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'부탁드립니다',null,null,null,'I kindly ask',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'가능할까요?',null,null,null,'would it be possible?',4);
  nxt := nxt + 1;
  insert into units (level_id,name,slug,icon,order_index) values (lv,'레벨 시험 (Level Test)','test-upper','flag',nxt) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'Upper-Intermediate 레벨 시험 (Level Test)','level_test',80,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'"Even though I studied" — which is correct?',null,'["공부했는데도", "공부해서", "공부하면"]'::jsonb,'공부했는데도',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Most appropriate ending in a job interview:',null,'["-습니다", "-아/어요", "-야"]'::jsonb,'-습니다',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',3) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Politely suggest resting:',null,'["쉬는 게 어때요?", "쉬어", "쉬었어요"]'::jsonb,'쉬는 게 어때요?',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',4) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'환경',null,null,null,'environment',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'면접',null,null,null,'job interview',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'동료',null,null,null,'colleague',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'추천해요',null,null,null,'I recommend',4);
  select id into lv from levels where slug = 'advanced';
  select coalesce(max(order_index),0) into nxt from units where level_id = lv;
  nxt := nxt + 1;
  insert into units (level_id,name,slug,icon,order_index) values (lv,'시사 분석 (Current Affairs)','current-affairs','newspaper',nxt) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'뉴스 어휘 (News vocabulary)','standard',null,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'정책','policy','jeongchaek',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'경제','economy','gyeongje',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'보도','news report','bodo',null,null,3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'영향','influence/impact','yeonghyang',null,null,4);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'sentence_build',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Build: "It affects the economy."',null,'["경제에", "영향을", "줍니다"]'::jsonb,'경제에 영향을 줍니다',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'논설 표현 (Editorial style)','standard',null,2) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'주장하다','to argue/assert','jujanghada',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'분석','analysis','bunseok',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'결론','conclusion','gyeollon',null,null,3);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Which word means "conclusion"?',null,'["결론", "분석", "주장"]'::jsonb,'결론',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'시사 짝짓기 (News Match)','unlock_game',80,3) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'정책',null,null,null,'policy',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'경제',null,null,null,'economy',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'분석',null,null,null,'analysis',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'결론',null,null,null,'conclusion',4);
  nxt := nxt + 1;
  insert into units (level_id,name,slug,icon,order_index) values (lv,'발표와 토론 (Presenting & Debating)','presenting','mic',nxt) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'발표 표현 (Presentation phrases)','standard',null,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'발표','presentation','balpyo',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'말씀드리겠습니다','I will explain','malsseumdeurigesseumnida',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'정리하면','to summarise','jeongnihamyeon',null,null,3);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'You are opening a formal presentation. Which fits?',null,'["말씀드리겠습니다", "말할게", "말해요"]'::jsonb,'말씀드리겠습니다',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'반론 (Rebuttal)','standard',null,2) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'그러나','however','geureona',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'반면에','on the other hand','banmyeone',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'동의하기 어렵습니다','I find it hard to agree','dong-uihagi eoryeopseumnida',null,null,3);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'sentence_build',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Build: "On the other hand..."',null,'["반면에"]'::jsonb,'반면에',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'발표 게임 (Presentation Game)','unlock_game',80,3) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'발표',null,null,null,'presentation',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'그러나',null,null,null,'however',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'반면에',null,null,null,'on the other hand',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'정리하면',null,null,null,'to summarise',4);
  nxt := nxt + 1;
  insert into units (level_id,name,slug,icon,order_index) values (lv,'문학과 매체 (Literature & Media)','literature','book-open',nxt) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'비유 표현 (Figurative language)','standard',null,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'비유','metaphor/simile','biyu',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'상징','symbol','sangjing',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'작가','author','jakga',null,null,3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'주제','theme','juje',null,null,4);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Which word means "theme"?',null,'["주제", "상징", "작가"]'::jsonb,'주제',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'감상 표현 (Responding to a work)','standard',null,2) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'인상 깊었어요','it left an impression','insang gipeosseoyo',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'여운','lingering resonance','yeoun',null,null,2);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'sentence_build',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Build: "It left a deep impression."',null,'["인상", "깊었어요"]'::jsonb,'인상 깊었어요',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'문학 짝짓기 (Literature Match)','unlock_game',80,3) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'비유',null,null,null,'metaphor',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'상징',null,null,null,'symbol',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'작가',null,null,null,'author',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'주제',null,null,null,'theme',4);
  nxt := nxt + 1;
  insert into units (level_id,name,slug,icon,order_index) values (lv,'레벨 시험 (Level Test)','test-advanced','flag',nxt) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'Advanced 레벨 시험 (Advanced Level Test)','level_test',80,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Which means "conclusion"?',null,'["결론", "분석", "보도"]'::jsonb,'결론',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Formal presentation opener:',null,'["말씀드리겠습니다", "말할게", "말해요"]'::jsonb,'말씀드리겠습니다',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',3) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Which means "theme"?',null,'["주제", "여운", "상징"]'::jsonb,'주제',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',4) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'정책',null,null,null,'policy',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'반면에',null,null,null,'on the other hand',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'작가',null,null,null,'author',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'영향',null,null,null,'impact',4);
  select id into lv from levels where slug = 'beginner';
  select coalesce(max(order_index),0) into nxt from units where level_id = lv;
  nxt := nxt + 1;
  insert into units (level_id,name,slug,icon,order_index) values (lv,'레벨 시험 (Level Test)','test-beginner','flag',nxt) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'Beginner 레벨 시험 (Beginner Level Test)','level_test',80,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Your teacher stays behind as you leave. What do you say?',null,'["안녕히 계세요", "안녕히 가세요", "반가워요"]'::jsonb,'안녕히 계세요',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Which is the polite form of 오다 (to come)?',null,'["와요", "오어요", "오해요"]'::jsonb,'와요',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',3) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Which number is 삼?',null,'["3", "2", "4"]'::jsonb,'3',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',4) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'안녕하세요?',null,null,null,'Hello',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'책',null,null,null,'book',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'있어요',null,null,null,'there is',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'월요일',null,null,null,'Monday',4);
end $$;
