do $$
declare lv uuid; un uuid; ls uuid; ex uuid;
begin
  insert into levels (name,slug,description,order_index,test_threshold_pct)
  values ('Hangul Basics','hangul-basics','Read Hangul from scratch — no prior knowledge needed',0,80)
  on conflict (slug) do nothing;
  select id into lv from levels where slug='hangul-basics';
  insert into units (level_id,name,slug,icon,order_index) values (lv,'자음 1 (First Consonants)','consonants-1','pencil',1) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'소리 배우기 (Learn the sounds)','standard',null,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㄱ','g / k sound','giyeok',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㄴ','n sound','nieun',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㄷ','d / t sound','digeut',null,null,3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㄹ','r / l sound','rieul',null,null,4);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㅁ','m sound','mieum',null,null,5);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Which letter makes the “m” sound?',null,'["ㅁ", "ㄴ", "ㄱ"]'::jsonb,'ㅁ',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'다시 확인 (Check yourself)','standard',null,2) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Which letter makes the “n” sound?',null,'["ㄴ", "ㄷ", "ㄹ"]'::jsonb,'ㄴ',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Which letter makes the “g/k” sound?',null,'["ㄱ", "ㅁ", "ㄹ"]'::jsonb,'ㄱ',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'자음 게임 1 (Consonant Game 1)','unlock_game',80,3) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㄱ',null,null,null,'g / k',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㄴ',null,null,null,'n',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㄷ',null,null,null,'d / t',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㅁ',null,null,null,'m',4);
  insert into units (level_id,name,slug,icon,order_index) values (lv,'자음 2 (More Consonants)','consonants-2','pencil',2) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'소리 배우기 (Learn the sounds)','standard',null,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㅂ','b / p sound','bieup',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㅅ','s sound','siot',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㅇ','silent at the start, “ng” at the end','ieung',null,null,3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㅈ','j sound','jieut',null,null,4);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㅎ','h sound','hieut',null,null,5);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'At the START of a syllable, ㅇ is…',null,'["silent", "an “o” sound", "an “ng” sound"]'::jsonb,'silent',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'다시 확인 (Check yourself)','standard',null,2) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Which letter makes the “s” sound?',null,'["ㅅ", "ㅈ", "ㅎ"]'::jsonb,'ㅅ',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Which letter makes the “h” sound?',null,'["ㅎ", "ㅂ", "ㅇ"]'::jsonb,'ㅎ',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'자음 게임 2 (Consonant Game 2)','unlock_game',80,3) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㅂ',null,null,null,'b / p',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㅅ',null,null,null,'s',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㅈ',null,null,null,'j',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㅎ',null,null,null,'h',4);
  insert into units (level_id,name,slug,icon,order_index) values (lv,'모음 (The Vowels)','vowels','sun',3) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'기본 모음 (Basic vowels)','standard',null,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㅏ','“ah” as in father','a',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㅓ','“uh” as in mother','eo',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㅗ','“oh” as in go','o',null,null,3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㅜ','“oo” as in food','u',null,null,4);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㅡ','“eu”, lips flat','eu',null,null,5);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㅣ','“ee” as in see','i',null,null,6);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Which vowel sounds like “ee” in see?',null,'["ㅣ", "ㅡ", "ㅜ"]'::jsonb,'ㅣ',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'다시 확인 (Check yourself)','standard',null,2) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Which vowel sounds like “oh”?',null,'["ㅗ", "ㅏ", "ㅓ"]'::jsonb,'ㅗ',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Which vowel sounds like “ah”?',null,'["ㅏ", "ㅜ", "ㅣ"]'::jsonb,'ㅏ',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'모음 게임 (Vowel Game)','unlock_game',80,3) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㅏ',null,null,null,'ah',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㅗ',null,null,null,'oh',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㅜ',null,null,null,'oo',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㅣ',null,null,null,'ee',4);
  insert into units (level_id,name,slug,icon,order_index) values (lv,'글자 만들기 (Building Syllables)','syllables','blocks',4) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'자음 + 모음 (Consonant + vowel)','standard',null,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'가','ㄱ + ㅏ','ga',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'나','ㄴ + ㅏ','na',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'마','ㅁ + ㅏ','ma',null,null,3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'바','ㅂ + ㅏ','ba',null,null,4);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'사','ㅅ + ㅏ','sa',null,null,5);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'ㄴ + ㅏ makes which syllable?',null,'["나", "가", "마"]'::jsonb,'나',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'더 만들기 (Make more)','standard',null,2) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'고','ㄱ + ㅗ','go',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'무','ㅁ + ㅜ','mu',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'시','ㅅ + ㅣ','si',null,null,3);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'ㅁ + ㅜ makes which syllable?',null,'["무", "모", "미"]'::jsonb,'무',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'글자 게임 (Syllable Game)','unlock_game',80,3) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'가',null,null,null,'ga',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'나',null,null,null,'na',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'고',null,null,null,'go',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'무',null,null,null,'mu',4);
  insert into units (level_id,name,slug,icon,order_index) values (lv,'받침 (Final Consonants)','batchim','layers',5) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'받침이란? (What is a batchim?)','standard',null,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'안','a consonant UNDER the syllable','an',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'밥','rice / meal','bap',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'물','water','mul',null,null,3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'김','seaweed','gim',null,null,4);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'In 밥, which letter is the batchim (the bottom one)?',null,'["ㅂ", "ㅏ", "ㅁ"]'::jsonb,'ㅂ',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'읽어 보기 (Try reading)','standard',null,2) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'How do you read 물?',null,'["mul", "mu", "mil"]'::jsonb,'mul',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'How do you read 김?',null,'["gim", "ga", "gum"]'::jsonb,'gim',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'받침 게임 (Batchim Game)','unlock_game',80,3) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'밥',null,null,null,'rice / meal',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'물',null,null,null,'water',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'김',null,null,null,'seaweed',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'안',null,null,null,'inside / not',4);
  insert into units (level_id,name,slug,icon,order_index) values (lv,'숫자 (Numbers 1–5)','numbers-basic','hash',6) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'한자 숫자 (Sino-Korean numbers)','standard',null,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'일','1','il',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'이','2','i',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'삼','3','sam',null,null,3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'사','4','sa',null,null,4);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'오','5','o',null,null,5);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Which one means 3?',null,'["삼", "이", "오"]'::jsonb,'삼',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'고유어 숫자 (Native Korean numbers)','standard',null,2) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'vocab_card',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'하나','1 (for counting things)','hana',null,null,1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'둘','2','dul',null,null,2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'셋','3','set',null,null,3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'넷','4','net',null,null,4);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'다섯','5','daseot',null,null,5);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Counting 3 apples, you use…',null,'["셋", "삼", "사"]'::jsonb,'셋',1);
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'숫자 게임 (Number Game)','unlock_game',80,3) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'일',null,null,null,'1',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'삼',null,null,null,'3',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'하나',null,null,null,'1 (counting)',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'다섯',null,null,null,'5',4);
  insert into units (level_id,name,slug,icon,order_index) values (lv,'레벨 시험 (Level Test)','test-hangul','flag',7) returning id into un;
  insert into lessons (unit_id,name,lesson_type,unlock_threshold_pct,order_index) values (un,'한글 기초 레벨 시험 (Hangul Basics Level Test)','level_test',80,1) returning id into ls;
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',1) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Which letter makes the “m” sound?',null,'["ㅁ", "ㄴ", "ㅂ"]'::jsonb,'ㅁ',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',2) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'Which vowel sounds like “ee” in see?',null,'["ㅣ", "ㅗ", "ㅡ"]'::jsonb,'ㅣ',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',3) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'ㄱ + ㅏ makes which syllable?',null,'["가", "나", "고"]'::jsonb,'가',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'multiple_choice',4) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,null,'How do you read 물?',null,'["mul", "mil", "mu"]'::jsonb,'mul',1);
  insert into exercises (lesson_id,exercise_type,order_index) values (ls,'matching',5) returning id into ex;
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'일',null,null,null,'1',1);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'셋',null,null,null,'3 (counting)',2);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'밥',null,null,null,'rice / meal',3);
  insert into exercise_questions (exercise_id,prompt_ko,prompt_en,romanization,options,correct_answer,order_index) values (ex,'ㅎ',null,null,null,'h sound',4);
end $$;
